version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@1
  heroku: circleci/heroku@1.2.6

jobs:
  test:
      cypress/run:
          command: npx cypress run --headless --component
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages: #If you are using Yarn change this to Yarn
          pkg-manager: npm
      - run : 
          name : Run build
          command: npm run build #If you are using Yarn change this to Yarn
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true
workflows:
  test_my_app:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main