version: 2.1

orbs:
  node: circleci/node@5.1.0
  cypress: cypress-io/cypress@3
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run : 
          name : Run build
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true
workflows:
  test_my_app:
    jobs:
      - cypress/run:
          start-command: 'npm run start'
          cypress-command: 'npx cypress run'
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main