version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@3.1.3
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages: #If you are using Yarn change this to Yarn
          pkg-manager: npm
      - run : 
          name : Run build
          command: npm run build #If you are using Yarn change this to Yarn
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  test:
    - cypress/run:
      start: npm start
      cypress-command: npx cypress run --browser chrome
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Deploy Main to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
workflows:
  test_my_app:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main