version: 2.1

orbs:
  node: circleci/node@4.7
  cypress: cypress-io/cypress@3
  heroku: circleci/heroku@1.2.6

jobs:
  store:
      working_directory: /tmp
      steps:
        - run:
            name: Creating Dummy Artifacts
            command: |
              echo "my artifact file" > /tmp/art-1;
              mkdir /tmp/artifacts;
              echo "my artifact files in a dir" > /tmp/artifacts/art-2;
        - store_artifacts:
            path: /tmp/art-1
            destination: artifact-file
        - store_artifacts:
            path: /tmp/artifacts
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages: #If you are using Yarn change this to Yarn
          pkg-manager: npm
      - run : 
          name : Run build
          command: npm run build #If you are using Yarn change this to Yarn
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true
workflows:
  test_my_app:
    jobs:
      - cypress/run:
          start-command: 'npm run start'
          cypress-command: 'npx cypress run'
      - build
      - store
      - deploy:
          requires:
            - build # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main